-- =============================================================
-- GPA MAX - SUPABASE FREE DATABASE SCHEMA SCRIPT
-- Paste this script into your Supabase SQL Editor and click "Run"
-- =============================================================

BEGIN;

-- 1. Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
  id TEXT PRIMARY KEY,
  profile_id TEXT DEFAULT '',
  profile_name TEXT NOT NULL,
  university TEXT NOT NULL,
  faculty TEXT NOT NULL,
  department TEXT DEFAULT '',
  degree TEXT DEFAULT '',
  academic_year TEXT DEFAULT '',
  description TEXT DEFAULT '',
  visibility TEXT DEFAULT 'public',
  password_hash TEXT DEFAULT '',
  passcode_hash TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS search_text TEXT NOT NULL DEFAULT '';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS semester_names TEXT NOT NULL DEFAULT '';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS semester_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS subject_count INTEGER NOT NULL DEFAULT 0;

-- Indexes for ultra-fast filtering & searching
CREATE INDEX IF NOT EXISTS idx_profiles_id ON public.profiles(id);
CREATE INDEX IF NOT EXISTS idx_profiles_name ON public.profiles(profile_name);
CREATE INDEX IF NOT EXISTS idx_profiles_university ON public.profiles(university);
CREATE INDEX IF NOT EXISTS idx_profiles_faculty ON public.profiles(faculty);

CREATE INDEX IF NOT EXISTS idx_profiles_academic_year ON public.profiles(academic_year);
CREATE INDEX IF NOT EXISTS idx_profiles_visibility ON public.profiles(visibility);

-- 2. Semesters Table
CREATE TABLE IF NOT EXISTS public.semesters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id TEXT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  semester_name TEXT NOT NULL,
  semester_order INT DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_semesters_profile_id ON public.semesters(profile_id);

-- 3. Subjects Table
CREATE TABLE IF NOT EXISTS public.subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  semester_id BIGINT NOT NULL REFERENCES public.semesters(id) ON DELETE CASCADE,
  subject_code TEXT DEFAULT '',
  module_number TEXT DEFAULT '',
  subject_name TEXT NOT NULL,
  credit NUMERIC NOT NULL,
  selected_grade TEXT DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_subjects_semester_id ON public.subjects(semester_id);
CREATE INDEX IF NOT EXISTS idx_subjects_subject_code ON public.subjects(subject_code);

-- 4. Grading Scales Table
CREATE TABLE IF NOT EXISTS public.grading_scales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id TEXT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  grade TEXT NOT NULL,
  grade_point NUMERIC NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_grading_scales_profile_id ON public.grading_scales(profile_id);

-- Safe Migration for existing Supabase projects
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS profile_id TEXT DEFAULT '';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS department TEXT DEFAULT '';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS degree TEXT DEFAULT '';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS password_hash TEXT DEFAULT '';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS passcode_hash TEXT DEFAULT '';
ALTER TABLE public.subjects ADD COLUMN IF NOT EXISTS module_number TEXT DEFAULT '';
ALTER TABLE public.subjects ADD COLUMN IF NOT EXISTS selected_grade TEXT DEFAULT '';

CREATE INDEX IF NOT EXISTS idx_profiles_department ON public.profiles(department);

-- Enable Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.semesters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.grading_scales ENABLE ROW LEVEL SECURITY;

-- Remove legacy permissive policies for all four tables.
DROP POLICY IF EXISTS "Public profiles read access" ON public.profiles;

DROP POLICY IF EXISTS "Public profiles insert access" ON public.profiles;

DROP POLICY IF EXISTS "Public profiles update access" ON public.profiles;

DROP POLICY IF EXISTS "Public profiles delete access" ON public.profiles;

DROP POLICY IF EXISTS "Public semesters read access" ON public.semesters;

DROP POLICY IF EXISTS "Public semesters insert access" ON public.semesters;

DROP POLICY IF EXISTS "Public semesters update access" ON public.semesters;

DROP POLICY IF EXISTS "Public semesters delete access" ON public.semesters;

DROP POLICY IF EXISTS "Public subjects read access" ON public.subjects;

DROP POLICY IF EXISTS "Public subjects insert access" ON public.subjects;

DROP POLICY IF EXISTS "Public subjects update access" ON public.subjects;

DROP POLICY IF EXISTS "Public subjects delete access" ON public.subjects;

DROP POLICY IF EXISTS "Public grading scales read access" ON public.grading_scales;

DROP POLICY IF EXISTS "Public grading scales insert access" ON public.grading_scales;

DROP POLICY IF EXISTS "Public grading scales update access" ON public.grading_scales;

DROP POLICY IF EXISTS "Public grading scales delete access" ON public.grading_scales;

-- Enable Row Level Security (RLS) and grant SELECT and INSERT access to anon & authenticated for public profiles
GRANT ALL ON TABLE public.profiles, public.semesters, public.subjects, public.grading_scales TO service_role;
REVOKE ALL ON TABLE public.profiles, public.semesters, public.subjects, public.grading_scales FROM anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.semesters_id_seq, public.subjects_id_seq, public.grading_scales_id_seq TO service_role;
REVOKE ALL ON SEQUENCE public.semesters_id_seq, public.subjects_id_seq, public.grading_scales_id_seq FROM anon, authenticated;

DROP POLICY IF EXISTS "Public profiles select policy" ON public.profiles;
CREATE POLICY "Public profiles select policy" ON public.profiles
  FOR SELECT TO service_role
  USING (true);

DROP POLICY IF EXISTS "Public profiles insert policy" ON public.profiles;
CREATE POLICY "Public profiles insert policy" ON public.profiles
  FOR INSERT TO service_role
  WITH CHECK (true);

DROP POLICY IF EXISTS "Public semesters select policy" ON public.semesters;
CREATE POLICY "Public semesters select policy" ON public.semesters
  FOR SELECT TO service_role
  USING (true);

DROP POLICY IF EXISTS "Public semesters insert policy" ON public.semesters;
CREATE POLICY "Public semesters insert policy" ON public.semesters
  FOR INSERT TO service_role
  WITH CHECK (true);

DROP POLICY IF EXISTS "Public subjects select policy" ON public.subjects;
CREATE POLICY "Public subjects select policy" ON public.subjects
  FOR SELECT TO service_role
  USING (true);

DROP POLICY IF EXISTS "Public subjects insert policy" ON public.subjects;
CREATE POLICY "Public subjects insert policy" ON public.subjects
  FOR INSERT TO service_role
  WITH CHECK (true);

DROP POLICY IF EXISTS "Public grading scales select policy" ON public.grading_scales;
CREATE POLICY "Public grading scales select policy" ON public.grading_scales
  FOR SELECT TO service_role
  USING (true);

DROP POLICY IF EXISTS "Public grading scales insert policy" ON public.grading_scales;
CREATE POLICY "Public grading scales insert policy" ON public.grading_scales
  FOR INSERT TO service_role
  WITH CHECK (true);


-- One RPC call is one PostgreSQL transaction. Any validation or insert failure
-- rolls back profile metadata, deletions, and all replacement rows together.
CREATE OR REPLACE FUNCTION public.save_gpa_profile(p_id text, p_data jsonb, p_create boolean)
RETURNS void
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  sem jsonb;
  sub jsonb;
  gs jsonb;
  sem_id bigint;
  sem_order integer := 0;
  credit_value numeric;
  grade_value numeric;
BEGIN
  IF coalesce(btrim(p_data->>'profile_name'), '') = '' THEN
    RAISE EXCEPTION 'Profile name is required';
  END IF;
  IF coalesce(p_data->>'visibility', 'public') NOT IN ('public', 'shared', 'private') THEN
    RAISE EXCEPTION 'Invalid visibility';
  END IF;
  IF p_create THEN
    INSERT INTO public.profiles (id, profile_id, profile_name, university, faculty, degree, passcode_hash, password_hash)
    VALUES (p_id, p_id, btrim(p_data->>'profile_name'), '', '',
      coalesce(p_data->>'degree', ''), coalesce(p_data->>'passcode_hash', ''), coalesce(p_data->>'passcode_hash', ''));
  ELSE
    PERFORM 1 FROM public.profiles WHERE id = p_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Profile not found'; END IF;
  END IF;

  UPDATE public.profiles SET
    profile_name = btrim(p_data->>'profile_name'),
    university = coalesce(btrim(p_data->>'university'), ''),
    faculty = coalesce(btrim(p_data->>'faculty'), ''),
    department = coalesce(btrim(p_data->>'department'), ''),
    degree = coalesce(btrim(p_data->>'degree'), ''),
    academic_year = coalesce(btrim(p_data->>'academic_year'), ''),
    description = coalesce(btrim(p_data->>'description'), ''),
    visibility = coalesce(p_data->>'visibility', 'public'),
    updated_at = now()
  WHERE id = p_id;

  DELETE FROM public.semesters WHERE profile_id = p_id;
  DELETE FROM public.grading_scales WHERE profile_id = p_id;
  FOR sem IN SELECT value FROM jsonb_array_elements(coalesce(p_data->'semesters', '[]'::jsonb)) LOOP
    sem_order := sem_order + 1;
    INSERT INTO public.semesters (profile_id, semester_name, semester_order)
    VALUES (p_id, coalesce(nullif(sem->>'semester_name', ''), 'Semester ' || sem_order), sem_order)
    RETURNING id INTO sem_id;
    FOR sub IN SELECT value FROM jsonb_array_elements(coalesce(sem->'subjects', '[]'::jsonb)) LOOP
      credit_value := (sub->>'credit')::numeric;
      IF credit_value IS NULL OR credit_value < 0 OR credit_value::text IN ('NaN', 'Infinity', '-Infinity')
         OR coalesce(btrim(sub->>'subject_name'), '') = '' THEN
        RAISE EXCEPTION 'Invalid subject name or credit';
      END IF;
      INSERT INTO public.subjects (semester_id, subject_code, module_number, subject_name, credit, selected_grade)
      VALUES (sem_id, coalesce(sub->>'subject_code', ''), coalesce(sub->>'subject_code', ''), btrim(sub->>'subject_name'), credit_value, coalesce(sub->>'selected_grade', ''));
    END LOOP;
  END LOOP;
  FOR gs IN SELECT value FROM jsonb_array_elements(coalesce(p_data->'gradingScale', '[]'::jsonb)) LOOP
    grade_value := (gs->>'grade_point')::numeric;
    IF grade_value IS NULL OR grade_value < 0 OR grade_value::text IN ('NaN', 'Infinity', '-Infinity')
       OR coalesce(btrim(gs->>'grade'), '') = '' THEN
      RAISE EXCEPTION 'Invalid grading scale';
    END IF;
    INSERT INTO public.grading_scales (profile_id, grade, grade_point)
    VALUES (p_id, btrim(gs->>'grade'), grade_value);
  END LOOP;
  UPDATE public.profiles SET
    search_text = concat_ws(' ', profile_name, university, faculty, department, degree, academic_year, p_id,
      (SELECT string_agg(concat_ws(' ', sub.subject_code, sub.subject_name), ' ')
       FROM public.subjects sub JOIN public.semesters sem ON sem.id = sub.semester_id
       WHERE sem.profile_id = p_id)),
    semester_names = coalesce((SELECT string_agg(semester_name, ' ') FROM public.semesters WHERE profile_id = p_id), ''),
    semester_count = (SELECT count(*) FROM public.semesters WHERE profile_id = p_id),
    subject_count = (SELECT count(*) FROM public.subjects sub JOIN public.semesters sem ON sem.id = sub.semester_id WHERE sem.profile_id = p_id)
  WHERE id = p_id;
END;
$$;
REVOKE ALL ON FUNCTION public.save_gpa_profile(text, jsonb, boolean) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.save_gpa_profile(text, jsonb, boolean) TO service_role;

-- Populate the search columns for profiles created before this migration.
UPDATE public.profiles p SET
  search_text = concat_ws(' ', p.profile_name, p.university, p.faculty, p.department, p.degree, p.academic_year, p.id,
    (SELECT string_agg(concat_ws(' ', sub.subject_code, sub.subject_name), ' ')
     FROM public.subjects sub JOIN public.semesters sem ON sem.id = sub.semester_id WHERE sem.profile_id = p.id)),
  semester_names = coalesce((SELECT string_agg(semester_name, ' ') FROM public.semesters WHERE profile_id = p.id), ''),
  semester_count = (SELECT count(*) FROM public.semesters WHERE profile_id = p.id),
  subject_count = (SELECT count(*) FROM public.subjects sub JOIN public.semesters sem ON sem.id = sub.semester_id WHERE sem.profile_id = p.id);

COMMIT;
